version: '3'

services:
  app:
    build: .
    restart: always
    depends_on:
      - redis_db
      - postgres_db

  redis_db:
    image: "redis:alpine"
    restart: always
    volumes:
      - redis_data:/data

  postgres_db:
    image: "postgres:alpine"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data:


