name: workflow_sample
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m pytest
  
  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: Print Congrats
        run: echo 'Congrats!!!'
    
